image: openjdk:11

before_script:
  # Set up Android SDK paths
  - export ANDROID_HOME="${PWD}/android-home"
  - export ANDROID_SDK_ROOT=$ANDROID_HOME
  - export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH

  # Download & Install Command Line Tools
  - mkdir -p $ANDROID_HOME/cmdline-tools
  - wget -q "https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip" -O cmdline-tools.zip
  - unzip -q -d $ANDROID_HOME/cmdline-tools cmdline-tools.zip
  - mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

  # Accept Android SDK licenses
  - yes | sdkmanager --licenses
  - sdkmanager --update
  - sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

stages:
  - build
  - test

assemble_debug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    when: always
    expire_in: 30 days
    paths:
	- app/build/outputs/apk/debug/app-debug.apk


unit_tests:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    when: always
    expire_in: 30 days
    paths:   
      - app/build/reports/tests/

lint_debug:
  stage: test
  script:
    - ./gradlew lintDebug
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - app/build/reports/lint-results-debug.html

