image: openjdk:17-slim

variables:
  ANDROID_COMPILE_SDK: "33"
  ANDROID_BUILD_TOOLS: "33.0.2"
  ANDROID_HOME: "$CI_PROJECT_DIR/android-home"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - android-home

before_script:
  - apt-get update && apt-get install -y wget tar unzip lib32stdc++6 lib32z1
  - mkdir -p "$ANDROID_HOME"
  - wget --output-document=$ANDROID_HOME/cmdline-tools.zip "https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip"
  - unzip -q $ANDROID_HOME/cmdline-tools.zip -d $ANDROID_HOME/
  - mv $ANDROID_HOME/cmdline-tools $ANDROID_HOME/tools
  - yes | $ANDROID_HOME/tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools" "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS}"
  - echo "sdk.dir=$ANDROID_HOME" > local.properties
  - chmod +x ./gradlew

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assembleDebug

test:
  stage: test
  script:
    - ./gradlew lintDebug testDebugUnitTest
