image: openjdk:11

variables:
  ANDROID_COMPILE_SDK: "29"
  ANDROID_BUILD_TOOLS: "29.0.3"
  ANDROID_SDK_TOOLS: "9477386"

before_script:
  - apt-get --quiet update --yes && apt-get --quiet install --yes wget tar unzip lib32stdc++6 lib32z1
  - export ANDROID_HOME="${PWD}/android-home"
  - export ANDROID_SDK_ROOT=$ANDROID_HOME
  - mkdir -p $ANDROID_HOME
  - wget --output-document=$ANDROID_HOME/cmdline-tools.zip "https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip"
  - pushd $ANDROID_HOME
  - unzip -q cmdline-tools.zip
  - rm -f cmdline-tools.zip  # Remove the zip file after extraction to avoid conflicts
  - mv cmdline-tools cmdline-tools-temp  # Move extracted folder to a temp directory
  - mkdir -p cmdline-tools/latest  # Create the correct structure
  - mv cmdline-tools-temp/* cmdline-tools/latest/  # Move contents correctly
  - rm -rf cmdline-tools-temp  # Clean up the temp folder
  - popd
  - export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator:$PATH
  - which sdkmanager
  - sdkmanager --version
  - yes | sdkmanager --sdk_root=${ANDROID_HOME} --licenses || true
  - sdkmanager --sdk_root=${ANDROID_HOME} "platforms;android-${ANDROID_COMPILE_SDK}"
  - sdkmanager --sdk_root=${ANDROID_HOME} "platform-tools"
  - sdkmanager --sdk_root=${ANDROID_HOME} "build-tools;${ANDROID_BUILD_TOOLS}"
  - chmod +x ./gradlew

lintDebug:
  stage: build
  script:
    - ./gradlew -Pci --console=plain :app:lintDebug -PbuildDir=lint

assembleDebug:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/

debugTests:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :app:testDebug

unit_tests:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    when: always
    expire_in: 30 days
    paths:
      - app/build/reports/tests/

